In [2]:
import numpy as np

In [3]:
a = np.array([2, 3, 4])

In [4]:
a

array([2, 3, 4])

In [5]:
norm1 = np.linalg.norm(a, ord=1)

In [6]:
norm1

9.0

In [7]:
norm2 = np.linalg.norm(a, ord=2)

In [8]:
norm2

5.385164807134504

Расстояние между векторами

In [9]:
a = np.array([1, 2, 3])
b = np.array([0, 3, 2])

In [10]:
dist1 = np.linalg.norm(a - b, ord=1)
dist1

3.0

In [11]:
dist2 = np.linalg.norm(a - b, ord=2)
dist2

1.7320508075688772

### Также расстояние можно посчитать с помощью scipy

In [12]:
from scipy.spatial.distance import cdist

In [13]:
a = a.reshape((1, 3))
b = b.reshape((1, 3))

print(a, b)

[[1 2 3]] [[0 3 2]]


In [14]:
dist1_1 = cdist(a, b, metric='cityblock')

In [15]:
dist1_1

array([[3.]])

In [16]:
cdist(a, b)

array([[1.73205081]])

In [17]:
c = np.array([1, 2, 3])
d = np.array([0, 3, 2])

cdist(c[np.newaxis, :], d[np.newaxis, :])

array([[1.73205081]])

In [18]:
cdist(c[np.newaxis, :], d[np.newaxis, :], metric='cityblock')

array([[3.]])

In [19]:
A = np.matrix([[0, 1, 2], [3, 4, 5], [0, 2, 4]])

In [20]:
A

matrix([[0, 1, 2],
        [3, 4, 5],
        [0, 2, 4]])

In [21]:
B = np.matrix([[0, 1, 2], [3, 4, 5], [0, 2, 4]])
B

matrix([[0, 1, 2],
        [3, 4, 5],
        [0, 2, 4]])

In [22]:
cdist(A, B, metric='cosine')

array([[2.22044605e-16, 1.14562255e-01, 2.22044605e-16],
       [1.14562255e-01, 1.11022302e-16, 1.14562255e-01],
       [2.22044605e-16, 1.14562255e-01, 2.22044605e-16]])

In [23]:
np.dot(c, d)

12

In [34]:
c = np.array((0, 1, 2))
d = np.array((0, 2, 4))

print(c, d)

cos_angle = np.dot(c, d) / (np.linalg.norm(c, ord=2) * np.linalg.norm(d, ord=2))

[0 1 2] [0 2 4]


In [35]:
cos_angle

0.9999999999999998

In [36]:
cos_angle1 = cdist(c[np.newaxis, :], d[np.newaxis, :], metric='cosine')

In [37]:
cos_angle1

array([[2.22044605e-16]])

In [38]:
from scipy.spatial.distance import cosine

cos_angle1 = cosine(d, c)

In [39]:
cos_angle1

0.0

In [40]:
1 - cos_angle1

1.0

In [41]:
cdist(A[1:], A[0], metric='cosine')

array([[1.14562255e-01],
       [2.22044605e-16]])