In [6]:
import numpy as np

In [7]:
A = np.array([[5, 4, 3], [10, 8, 6]])

In [8]:
A

array([[ 5,  4,  3],
       [10,  8,  6]])

In [9]:
B = np.eye(3, 3)

In [12]:
B * 2

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [13]:
np.dot(A, B * 2)

array([[10.,  8.,  6.],
       [20., 16., 12.]])

In [14]:
 A * B # just dot-dot multiply - need the same size

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [16]:
B * np.ones((3, 3)) * 3

array([[3., 0., 0.],
       [0., 3., 0.],
       [0., 0., 3.]])

In [17]:
C = np.arange(0, 10, 1).reshape((5, 2))

In [18]:
C

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
C[:, 1]

array([1, 3, 5, 7, 9])

In [20]:
C[0, :]

array([0, 1])

In [21]:
C[2, 1]

5

In [24]:
np.arange(0, 10, 2)[np.newaxis, :]

array([[0, 2, 4, 6, 8]])

In [25]:
np.arange(0, 10, 2)[np.newaxis, :].T

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [26]:
np.transpose(np.array([[2, 3], [4, 5]]))

array([[2, 4],
       [3, 5]])

In [28]:
A = np.array([[2, 3], [3, 4]])
np.linalg.det(A)

-1.0000000000000004

In [29]:
np.linalg.matrix_rank(A)

2

In [33]:
a = np.array((1, 2, 3))
b = np.array((4, 3, 9))
c = 2*a + 3*b

mtrx = np.array((a, b, c))
mtrx

array([[ 1,  2,  3],
       [ 4,  3,  9],
       [14, 13, 33]])

In [34]:
np.linalg.matrix_rank(mtrx)

2

In [36]:
if (np.linalg.matrix_rank(A) == A.shape[0]):
    print("Векторы в матрице линейно независимы")

Векторы в матрице линейно независимы


In [37]:
A = np.array(((3, 1), (4, 3)))
b = np.array((5, 4))
x = np.linalg.solve(A, b)

In [38]:
x

array([ 2.2, -1.6])

In [48]:
np.dot(A, x)

array([5., 4.])

Если решений у системы нет, то хотелось бы найти приближенное. Для этого используем следующий метод

In [53]:
a = np.array([[0, 1], [1, 1], [2, 1], [3, 1]])
b = np.array([-1, 0.2, 0.9, 2.1])
x, res, r, s = np.linalg.lstsq(a, b)

In [54]:
x

array([ 1.  , -0.95])

Для нахождения обратной матрицы

In [55]:
np.linalg.inv(A)

array([[ 0.6, -0.2],
       [-0.8,  0.6]])

Собственные вектора и числа

В NumPy собственные числа и собственные векторы матрицы вычисляются с помощью функции numpy.linalg.eig(a), где a — исходная матрица. В качестве результата эта функция выдает одномерный массив w собственных чисел и двумерный массив v, в котором по столбцам записаны собственные вектора, так что вектор v[:, i] соотвествует собственному числу w[i].

In [56]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [58]:
w, v

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

In [62]:
A = np.array(((1, 1), (1, 2)))

In [63]:
A

array([[1, 1],
       [1, 2]])

In [65]:
np.dot(A, A.T)

array([[2, 3],
       [3, 5]])

In [66]:
np.linalg.inv(A)

array([[ 2., -1.],
       [-1.,  1.]])

In [67]:
np.eye(4, 5)[[0, 3], [1, 3]]

array([0., 1.])