In [1]:
import numpy as np

In [2]:
x = [2, 3, 4, 6]
y = np.array(x)

In [3]:
print(type(x), x)
print(type(y), y)

<class 'list'> [2, 3, 4, 6]
<class 'numpy.ndarray'> [2 3 4 6]


In [4]:
print(x[1:3])

[3, 4]


In [5]:
print(y[1:3])

[3 4]


In [6]:
x[[0, 2]]

TypeError: list indices must be integers or slices, not list

In [7]:
y[[0, 2]]

array([2, 4])

In [8]:
y[y > 3]

array([4, 6])

In [9]:
print(x * 5)

[2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6, 2, 3, 4, 6]


In [10]:
print(y * 5)

[10 15 20 30]


In [11]:
print(x ** 2)

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [12]:
print(y ** 2)

[ 4  9 16 36]


In [13]:
mtrx = [[1, 2, 4], [3, 1, 0]]
nd_array = np.array(mtrx)

In [14]:
mtrx

[[1, 2, 4], [3, 1, 0]]

In [15]:
nd_array

array([[1, 2, 4],
       [3, 1, 0]])

In [16]:
mtrx[1][2]

0

In [17]:
nd_array[1][2]

0

In [20]:
nd_array[1, 2]

0

In [18]:
nd_array[nd_array>2]

array([4, 3])

In [19]:
nd_array * 2

array([[2, 4, 8],
       [6, 2, 0]])

In [7]:
np.random.rand(4, 5)

array([[0.29556906, 0.77490472, 0.19711257, 0.53017979, 0.89581375],
       [0.66418893, 0.61353595, 0.18211225, 0.27832309, 0.59292328],
       [0.58494642, 0.70382578, 0.5543254 , 0.25813485, 0.95093669],
       [0.60182167, 0.23773221, 0.50488272, 0.57007505, 0.0297963 ]])

In [24]:
np.random.randn()

0.5981381422832754

In [25]:
np.random.randn(4)

array([ 0.67242984, -0.96999478, -0.59426648,  0.82715513])

In [26]:
np.random.randn(4, 5)

array([[-1.75405811, -0.10917909,  1.9164725 , -1.10797724, -0.68005966],
       [ 0.68539068,  0.02055285,  1.1303322 ,  1.39660805, -0.97984157],
       [-0.09685353,  0.22616283, -0.09291584, -2.51600576,  2.74639809],
       [-0.05496672,  0.78418516,  0.27425235, -0.95998074,  0.48274155]])

In [27]:
np.arange(0, 8, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9])

In [32]:
list(range(0, 8, 0.1))

TypeError: 'float' object cannot be interpreted as an integer

In [33]:
%timeit np.arange(0, 10000)
%timeit list(range(0, 10000))

7.66 µs ± 227 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
176 µs ± 1.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
