In [1]:
from scipy import optimize

In [2]:
def f(x):
    return (x[0] - 3.2) ** 2 + (x[1] - 0.1) ** 2 + 3

In [4]:
print(f((3.2, 0.1)))

3.0


In [5]:
x_min = optimize.minimize(f, (5, 5))

In [6]:
x_min

      fun: 3.0000000000011435
 hess_inv: array([[ 0.94055055, -0.16183475],
       [-0.16183475,  0.55944947]])
      jac: array([-2.05636024e-06,  5.36441803e-07])
  message: 'Optimization terminated successfully.'
     nfev: 12
      nit: 3
     njev: 4
   status: 0
  success: True
        x: array([3.19999896, 0.10000026])

In [7]:
x_min.x

array([3.19999896, 0.10000026])

In [8]:
from scipy import linalg

In [9]:
import numpy as np

In [10]:
A = np.array([[3, 2, 0], [1, -1, 0], [0, 5, 1]])
B = np.array([2, 4, -1])

X = linalg.solve(A, B)
X

array([ 2., -2.,  9.])

In [11]:
np.dot(A, X) # умножение матриц друг на друга (векторов np.array)

array([ 2.,  4., -1.])

In [19]:
X = np.random.randn(4, 3) * 1000 % 10
print(X)
U, D, V = linalg.svd(X)
print(U.shape, D.shape, V.shape)
print(U, D, V, sep='\n-----------------\n')

[[3.11910209 2.4267261  3.53938112]
 [8.41913051 2.04625088 5.27388649]
 [1.43448343 1.87961135 7.53947856]
 [6.21914711 9.75614358 8.07442367]]
(4, 4) (3,) (3, 3)
[[-0.28445117  0.06735877 -0.0354227  -0.95566498]
 [-0.49085062  0.84529539 -0.04026199  0.20717226]
 [-0.36208653 -0.28173391 -0.88033391  0.12054694]
 [-0.73962596 -0.44895936  0.4713135   0.1710337 ]]
-----------------
[18.60155633  5.22192612  4.38545893]
-----------------
[[-0.54506285 -0.51561103 -0.6610989 ]
 [ 0.7909848  -0.57766318 -0.2016142 ]
 [ 0.27793799  0.6328116  -0.72270323]]
