In [2]:
from sklearn import datasets, model_selection

In [3]:
iris = datasets.load_iris()

In [4]:
train_data, test_data, train_labels, test_labels = model_selection.train_test_split(iris.data, iris.target, test_size=0.3)

In [6]:
len(test_labels)/len(iris.data)

0.3

In [7]:
len(train_data)

105

In [8]:
len(test_data)

45

In [9]:
train_data[:5]

array([[5.8, 2.7, 5.1, 1.9],
       [6.4, 2.8, 5.6, 2.1],
       [5.4, 3.9, 1.7, 0.4],
       [7.4, 2.8, 6.1, 1.9],
       [6. , 2.9, 4.5, 1.5]])

In [10]:
train_labels

array([2, 2, 0, 2, 1, 2, 0, 1, 2, 1, 2, 0, 1, 0, 1, 2, 0, 1, 1, 0, 2, 0,
       1, 2, 2, 1, 1, 1, 1, 1, 0, 2, 1, 2, 0, 0, 1, 1, 2, 2, 2, 1, 1, 0,
       0, 1, 0, 2, 0, 2, 2, 2, 1, 1, 2, 0, 0, 1, 1, 0, 0, 0, 1, 2, 1, 0,
       0, 2, 0, 1, 0, 0, 0, 2, 2, 0, 2, 1, 2, 0, 0, 2, 2, 2, 2, 1, 2, 0,
       2, 0, 1, 2, 0, 1, 2, 0, 0, 0, 2, 0, 2, 0, 1, 0, 1])

In [12]:
test_labels

array([1, 1, 0, 1, 2, 1, 2, 1, 0, 2, 2, 2, 0, 2, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 0, 0, 1, 0, 2, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2,
       2])

In [22]:
X = range(12)

In [23]:
kf = model_selection.KFold(n_splits=6)

for train_indeces, test_indeces in kf.split(X):
    print(train_indeces, test_indeces)

[ 2  3  4  5  6  7  8  9 10 11] [0 1]
[ 0  1  4  5  6  7  8  9 10 11] [2 3]
[ 0  1  2  3  6  7  8  9 10 11] [4 5]
[ 0  1  2  3  4  5  8  9 10 11] [6 7]
[ 0  1  2  3  4  5  6  7 10 11] [8 9]
[0 1 2 3 4 5 6 7 8 9] [10 11]


In [27]:
kf = model_selection.KFold(n_splits=4, shuffle=True)

for train_indeces, test_indeces in kf.split(X):
    print(train_indeces, test_indeces)

[ 0  1  3  5  6  7  8  9 10] [ 2  4 11]
[ 0  1  2  4  5  7  8 10 11] [3 6 9]
[ 2  3  4  5  6  7  9 10 11] [0 1 8]
[ 0  1  2  3  4  6  8  9 11] [ 5  7 10]


In [29]:
kf = model_selection.KFold(n_splits=12, shuffle=True, random_state=12)

# leave one out cause n_splits = len(X)
for train_indeces, test_indeces in kf.split(X):
    print(train_indeces, test_indeces)

[ 0  1  2  3  4  5  6  7  8  9 11] [10]
[ 0  1  2  3  4  6  7  8  9 10 11] [5]
[ 0  1  2  3  4  5  6  7  8 10 11] [9]
[ 0  1  2  3  4  5  6  7  9 10 11] [8]
[ 1  2  3  4  5  6  7  8  9 10 11] [0]
[ 0  1  2  3  5  6  7  8  9 10 11] [4]
[ 0  1  2  3  4  5  6  8  9 10 11] [7]
[ 0  1  2  4  5  6  7  8  9 10 11] [3]
[ 0  1  3  4  5  6  7  8  9 10 11] [2]
[ 0  2  3  4  5  6  7  8  9 10 11] [1]
[ 0  1  2  3  4  5  7  8  9 10 11] [6]
[ 0  1  2  3  4  5  6  7  8  9 10] [11]


In [36]:
# стратификация для сохранения одинакового количества объектов каждого класса в выборках
import numpy as np

target = np.array([0, 1]  * 6)

skf = model_selection.StratifiedKFold(n_splits=3, shuffle=True, random_state=1)

for train_indeces, test_indeces in skf.split(X, target):
    print(train_indeces, test_indeces)

[ 0  1  3  4  7  8  9 10] [ 2  5  6 11]
[ 1  2  4  5  6  7 10 11] [0 3 8 9]
[ 0  2  3  5  6  8  9 11] [ 1  4  7 10]


In [37]:
# shuffle split - allow us to split our data how many times we want and one object can repeat any times

In [38]:
ss = model_selection.ShuffleSplit(n_splits=10, test_size=0.2)

for train_indeces, test_indeces in ss.split(X):
    print(train_indeces, test_indeces)

[10  8  1  2  9  0  5  6  4] [11  7  3]
[ 4 11  8 10  9  0  1  6  7] [3 5 2]
[ 7  3 11 10  5  4  0  8  9] [2 6 1]
[ 2  1  9  4  6  7  0  8 11] [ 5 10  3]
[ 7  2  1  0  9  8  6 10  4] [ 5 11  3]
[ 3  5 11  7  4  8  9  0  2] [10  6  1]
[ 9  4  8  0  3 10  6 11  2] [1 7 5]
[ 5  8  9 10  3  0  1  2  6] [11  7  4]
[ 2  6  1 11 10  8  0  3  5] [7 4 9]
[ 4  7  3 11  5  0  1 10  2] [9 8 6]


In [42]:
sss = model_selection.StratifiedShuffleSplit(n_splits=10, test_size=0.3)

for train_indeces, test_indeces in sss.split(X, target):
    print(train_indeces, test_indeces)

[ 8  6 11  4  9  1 10  3] [0 2 5 7]
[ 8  2  7  1  5  3  6 10] [ 9 11  4  0]
[ 0  1  3  7  6 10  9  2] [ 5 11  4  8]
[ 1  6 11 10  4  9  8  7] [5 3 2 0]
[ 2 11  9  6  5  0  3  4] [ 8  7  1 10]
[ 5  8  3  6 10  1  7  0] [11  4  9  2]
[ 8  3 10  6  5 11  1  2] [4 7 0 9]
[ 7  6 10  1  5  3  0  4] [ 9  2  8 11]
[10 11  9  0  3  6  5  8] [4 7 2 1]
[ 8  1  6  4 11  3 10  9] [7 0 2 5]


In [46]:
loo = model_selection.LeaveOneOut()

for train_indeces, test_indeces in loo.split(X):
    print(train_indeces, test_indeces)

[ 1  2  3  4  5  6  7  8  9 10 11] [0]
[ 0  2  3  4  5  6  7  8  9 10 11] [1]
[ 0  1  3  4  5  6  7  8  9 10 11] [2]
[ 0  1  2  4  5  6  7  8  9 10 11] [3]
[ 0  1  2  3  5  6  7  8  9 10 11] [4]
[ 0  1  2  3  4  6  7  8  9 10 11] [5]
[ 0  1  2  3  4  5  7  8  9 10 11] [6]
[ 0  1  2  3  4  5  6  8  9 10 11] [7]
[ 0  1  2  3  4  5  6  7  9 10 11] [8]
[ 0  1  2  3  4  5  6  7  8 10 11] [9]
[ 0  1  2  3  4  5  6  7  8  9 11] [10]
[ 0  1  2  3  4  5  6  7  8  9 10] [11]
